import { Flag } from '../types';

export const africaFlags: Flag[] = [
  {
    id: "za",
    type: "flag",
    name: "South Africa",
    country: "South Africa",
    flagUrl: "https://flagcdn.com/w320/za.png",
    imageUrl: "https://flagcdn.com/w320/za.png",
    description: "A colorful flag with six colors and a Y-shape in the center!",
    region: "Africa",
    capital: "Pretoria",
    population: "60 million",
    language: "11 official languages",
    funFact: "South Africa has three capital cities!",
    funFactReference: "https://www.britannica.com/topic/flag-of-South-Africa"
  },
  {
    id: "eg",
    type: "flag",
    name: "Egypt",
    country: "Egypt",
    flagUrl: "https://flagcdn.com/w320/eg.png",
    imageUrl: "https://flagcdn.com/w320/eg.png",
    description: "Three horizontal bands of red, white, and black with an eagle in the center!",
    region: "Africa",
    capital: "Cairo",
    population: "104 million",
    language: "Arabic",
    funFact: "The eagle on Egypt's flag is called the Eagle of Saladin!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Egypt"
  },
  {
    id: "ng",
    type: "flag",
    name: "Nigeria",
    country: "Nigeria",
    flagUrl: "https://flagcdn.com/w320/ng.png",
    imageUrl: "https://flagcdn.com/w320/ng.png",
    description: "Three vertical bands of green, white, and green!",
    region: "Africa",
    capital: "Abuja",
    population: "213 million",
    language: "English",
    funFact: "The green stripes represent Nigeria's forests and natural wealth!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Nigeria"
  },
  {
    id: "ke",
    type: "flag",
    name: "Kenya",
    country: "Kenya",
    flagUrl: "https://flagcdn.com/w320/ke.png",
    imageUrl: "https://flagcdn.com/w320/ke.png",
    description: "Three horizontal bands of black, red, and green with white edges and a shield in the center!",
    region: "Africa",
    capital: "Nairobi",
    population: "54 million",
    language: "Swahili, English",
    funFact: "The Maasai shield and spears represent defense of freedom!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Kenya"
  },
  {
    id: "ma",
    type: "flag",
    name: "Morocco",
    country: "Morocco",
    flagUrl: "https://flagcdn.com/w320/ma.png",
    imageUrl: "https://flagcdn.com/w320/ma.png",
    description: "A red field with a green pentagram (five-pointed star)!",
    region: "Africa",
    capital: "Rabat",
    population: "37 million",
    language: "Arabic, Berber",
    funFact: "The pentagram represents the seal of Solomon!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Morocco"
  },
  {
    id: "tz",
    type: "flag",
    name: "Tanzania",
    country: "Tanzania",
    flagUrl: "https://flagcdn.com/w320/tz.png",
    imageUrl: "https://flagcdn.com/w320/tz.png",
    description: "A diagonal yellow-edged black band between triangles of green and blue!",
    region: "Africa",
    capital: "Dodoma",
    population: "59.7 million",
    language: "Swahili, English",
    funFact: "The colors represent minerals, agriculture, and the Indian Ocean!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Tanzania"
  },
  {
    id: "ug",
    type: "flag",
    name: "Uganda",
    country: "Uganda",
    flagUrl: "https://flagcdn.com/w320/ug.png",
    imageUrl: "https://flagcdn.com/w320/ug.png",
    description: "Six horizontal stripes of black, yellow, red with a white disc and crane in the center!",
    region: "Africa",
    capital: "Kampala",
    population: "45.7 million",
    language: "English, Swahili",
    funFact: "The crane is the national symbol of Uganda!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Uganda"
  },
  {
    id: "sn",
    type: "flag",
    name: "Senegal",
    country: "Senegal",
    flagUrl: "https://flagcdn.com/w320/sn.png",
    imageUrl: "https://flagcdn.com/w320/sn.png",
    description: "Three vertical bands of green, yellow, and red with a green star in the center!",
    region: "Africa",
    capital: "Dakar",
    population: "16.7 million",
    language: "French",
    funFact: "The colors are the Pan-African colors!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Senegal"
  },
  {
    id: "rw",
    type: "flag",
    name: "Rwanda",
    country: "Rwanda",
    flagUrl: "https://flagcdn.com/w320/rw.png",
    imageUrl: "https://flagcdn.com/w320/rw.png",
    description: "Three horizontal bands of blue, yellow, and green with a sun in the blue band!",
    region: "Africa",
    capital: "Kigali",
    population: "13.2 million",
    language: "Kinyarwanda, English, French",
    funFact: "The sun represents new hope for the country!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Rwanda"
  },
  {
    id: "mg",
    type: "flag",
    name: "Madagascar",
    country: "Madagascar",
    flagUrl: "https://flagcdn.com/w320/mg.png",
    imageUrl: "https://flagcdn.com/w320/mg.png",
    description: "A white vertical band on the hoist side and red and green horizontal bands!",
    region: "Africa",
    capital: "Antananarivo",
    population: "27.7 million",
    language: "Malagasy, French",
    funFact: "The colors represent sovereignty, wealth, and hope!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Madagascar"
  },
  {
    id: "cm",
    type: "flag",
    name: "Cameroon",
    country: "Cameroon",
    flagUrl: "https://flagcdn.com/w320/cm.png",
    imageUrl: "https://flagcdn.com/w320/cm.png",
    description: "Three vertical bands of green, red, and yellow with a gold star in the center!",
    region: "Africa",
    capital: "Yaoundé",
    population: "26.5 million",
    language: "French, English",
    funFact: "The star is called the star of unity!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Cameroon"
  },
  {
    id: "ci",
    type: "flag",
    name: "Côte d'Ivoire",
    country: "Côte d'Ivoire",
    flagUrl: "https://flagcdn.com/w320/ci.png",
    imageUrl: "https://flagcdn.com/w320/ci.png",
    description: "Three vertical bands of orange, white, and green!",
    region: "Africa",
    capital: "Yamoussoukro",
    population: "26.4 million",
    language: "French",
    funFact: "The colors represent the savannah, forests, and coastal regions!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Côte-d'Ivoire"
  },
  {
    id: "ao",
    type: "flag",
    name: "Angola",
    country: "Angola",
    flagUrl: "https://flagcdn.com/w320/ao.png",
    imageUrl: "https://flagcdn.com/w320/ao.png",
    description: "Two horizontal bands of red and black with a yellow emblem in the center!",
    region: "Africa",
    capital: "Luanda",
    population: "32.9 million",
    language: "Portuguese",
    funFact: "The emblem includes a machete representing agricultural workers!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Angola"
  },
  {
    id: "dz",
    type: "flag",
    name: "Algeria",
    country: "Algeria",
    flagUrl: "https://flagcdn.com/w320/dz.png",
    imageUrl: "https://flagcdn.com/w320/dz.png",
    description: "Two vertical stripes of green and white with a red crescent and star in the center!",
    region: "Africa",
    capital: "Algiers",
    population: "44 million",
    language: "Arabic, Berber",
    funFact: "The white represents peace, and the green represents Islam!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Algeria"
  },
  {
    id: "zw",
    type: "flag",
    name: "Zimbabwe",
    country: "Zimbabwe",
    flagUrl: "https://flagcdn.com/w320/zw.png",
    imageUrl: "https://flagcdn.com/w320/zw.png",
    description: "Seven horizontal stripes with a white triangle containing a red star and bird!",
    region: "Africa",
    capital: "Harare",
    population: "15 million",
    language: "English, Shona, Ndebele",
    funFact: "The bird is the Zimbabwe Bird, an emblem found in the ruins of Great Zimbabwe!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Zimbabwe"
  },
  {
    id: "mz",
    type: "flag",
    name: "Mozambique",
    country: "Mozambique",
    flagUrl: "https://flagcdn.com/w320/mz.png",
    imageUrl: "https://flagcdn.com/w320/mz.png",
    description: "Three horizontal stripes with a red triangle containing a yellow star and other symbols!",
    region: "Africa",
    capital: "Maputo",
    population: "31 million",
    language: "Portuguese",
    funFact: "The flag is the only one in the world to feature a modern firearm (an AK-47)!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Mozambique"
  }
]; 