import { Flag } from '../types';

export const europeFlags: Flag[] = [
  {
    id: "fr",
    type: "flag",
    name: "France",
    country: "France",
    flagUrl: "https://flagcdn.com/w320/fr.png",
    imageUrl: "https://flagcdn.com/w320/fr.png",
    description: "Three vertical bands of blue, white, and red!",
    region: "Europe",
    capital: "Paris",
    population: "67 million",
    language: "French",
    funFact: "The flag is called 'Le Tricolore' and was first used during the French Revolution!",
    funFactReference: "https://www.britannica.com/topic/flag-of-France"
  },
  {
    id: "de",
    type: "flag",
    name: "Germany",
    country: "Germany",
    flagUrl: "https://flagcdn.com/w320/de.png",
    imageUrl: "https://flagcdn.com/w320/de.png",
    description: "Three horizontal bands of black, red, and gold!",
    region: "Europe",
    capital: "Berlin",
    population: "83 million",
    language: "German",
    funFact: "The colors were inspired by the uniforms of German soldiers during the Napoleonic Wars!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Germany"
  },
  {
    id: "it",
    type: "flag",
    name: "Italy",
    country: "Italy",
    flagUrl: "https://flagcdn.com/w320/it.png",
    imageUrl: "https://flagcdn.com/w320/it.png",
    description: "Three vertical bands of green, white, and red!",
    region: "Europe",
    capital: "Rome",
    population: "60 million",
    language: "Italian",
    funFact: "The green represents the country's plains and hills!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Italy"
  },
  {
    id: "gb",
    type: "flag",
    name: "United Kingdom",
    country: "United Kingdom",
    flagUrl: "https://flagcdn.com/w320/gb.png",
    imageUrl: "https://flagcdn.com/w320/gb.png",
    description: "A blue field with the combined crosses of St. George, St. Andrew, and St. Patrick!",
    region: "Europe",
    capital: "London",
    population: "67 million",
    language: "English",
    funFact: "It's called the Union Jack when flown at sea!",
    funFactReference: "https://www.britannica.com/topic/flag-of-the-United-Kingdom"
  },
  {
    id: "es",
    type: "flag",
    name: "Spain",
    country: "Spain",
    flagUrl: "https://flagcdn.com/w320/es.png",
    imageUrl: "https://flagcdn.com/w320/es.png",
    description: "Two horizontal red bands with a yellow band in between!",
    region: "Europe",
    capital: "Madrid",
    population: "47 million",
    language: "Spanish",
    funFact: "The coat of arms features the Pillars of Hercules!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Spain"
  },
  {
    id: "pl",
    type: "flag",
    name: "Poland",
    country: "Poland",
    flagUrl: "https://flagcdn.com/w320/pl.png",
    imageUrl: "https://flagcdn.com/w320/pl.png",
    description: "Two horizontal bands of white and red!",
    region: "Europe",
    capital: "Warsaw",
    population: "38 million",
    language: "Polish",
    funFact: "The white represents peace and the red represents bravery!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Poland"
  },
  {
    id: "ua",
    type: "flag",
    name: "Ukraine",
    country: "Ukraine",
    flagUrl: "https://flagcdn.com/w320/ua.png",
    imageUrl: "https://flagcdn.com/w320/ua.png",
    description: "Two horizontal bands of blue and yellow!",
    region: "Europe",
    capital: "Kyiv",
    population: "44 million",
    language: "Ukrainian",
    funFact: "The colors represent blue skies over golden wheat fields!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Ukraine"
  },
  {
    id: "nl",
    type: "flag",
    name: "Netherlands",
    country: "Netherlands",
    flagUrl: "https://flagcdn.com/w320/nl.png",
    imageUrl: "https://flagcdn.com/w320/nl.png",
    description: "Three horizontal bands of red, white, and blue!",
    region: "Europe",
    capital: "Amsterdam",
    population: "17.4 million",
    language: "Dutch",
    funFact: "It's the oldest tricolor flag still in use today!",
    funFactReference: "https://www.britannica.com/topic/flag-of-the-Netherlands"
  },
  {
    id: "gr",
    type: "flag",
    name: "Greece",
    country: "Greece",
    flagUrl: "https://flagcdn.com/w320/gr.png",
    imageUrl: "https://flagcdn.com/w320/gr.png",
    description: "Nine horizontal stripes of blue and white with a cross in the canton!",
    region: "Europe",
    capital: "Athens",
    population: "10.7 million",
    language: "Greek",
    funFact: "The stripes represent the syllables in 'Freedom or Death' in Greek!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Greece"
  },
  {
    id: "pt",
    type: "flag",
    name: "Portugal",
    country: "Portugal",
    flagUrl: "https://flagcdn.com/w320/pt.png",
    imageUrl: "https://flagcdn.com/w320/pt.png",
    description: "A field of green and red with the national coat of arms in the center!",
    region: "Europe",
    capital: "Lisbon",
    population: "10.3 million",
    language: "Portuguese",
    funFact: "The armillary sphere represents Portugal's role in navigation!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Portugal"
  },
  {
    id: "se",
    type: "flag",
    name: "Sweden",
    country: "Sweden",
    flagUrl: "https://flagcdn.com/w320/se.png",
    imageUrl: "https://flagcdn.com/w320/se.png",
    description: "A blue field with a yellow Nordic cross!",
    region: "Europe",
    capital: "Stockholm",
    population: "10.4 million",
    language: "Swedish",
    funFact: "It's one of the oldest national flags still in use!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Sweden"
  },
  {
    id: "no",
    type: "flag",
    name: "Norway",
    country: "Norway",
    flagUrl: "https://flagcdn.com/w320/no.png",
    imageUrl: "https://flagcdn.com/w320/no.png",
    description: "A red field with a blue Nordic cross outlined in white!",
    region: "Europe",
    capital: "Oslo",
    population: "5.4 million",
    language: "Norwegian",
    funFact: "The design was inspired by the Danish flag!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Norway"
  },
  {
    id: "dk",
    type: "flag",
    name: "Denmark",
    country: "Denmark",
    flagUrl: "https://flagcdn.com/w320/dk.png",
    imageUrl: "https://flagcdn.com/w320/dk.png",
    description: "A red field with a white Nordic cross!",
    region: "Europe",
    capital: "Copenhagen",
    population: "5.8 million",
    language: "Danish",
    funFact: "It's the oldest national flag still in use, dating back to 1219!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Denmark"
  },
  {
    id: "fi",
    type: "flag",
    name: "Finland",
    country: "Finland",
    flagUrl: "https://flagcdn.com/w320/fi.png",
    imageUrl: "https://flagcdn.com/w320/fi.png",
    description: "A white field with a blue Nordic cross!",
    region: "Europe",
    capital: "Helsinki",
    population: "5.5 million",
    language: "Finnish, Swedish",
    funFact: "The colors represent snow and lakes!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Finland"
  },
  {
    id: "ie",
    type: "flag",
    name: "Ireland",
    country: "Ireland",
    flagUrl: "https://flagcdn.com/w320/ie.png",
    imageUrl: "https://flagcdn.com/w320/ie.png",
    description: "Three vertical bands of green, white, and orange!",
    region: "Europe",
    capital: "Dublin",
    population: "5 million",
    language: "English, Irish",
    funFact: "The green represents the Catholic tradition, orange the Protestant!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Ireland"
  },
  {
    id: "be",
    type: "flag",
    name: "Belgium",
    country: "Belgium",
    flagUrl: "https://flagcdn.com/w320/be.png",
    imageUrl: "https://flagcdn.com/w320/be.png",
    description: "Three vertical stripes of black, yellow, and red!",
    region: "Europe",
    capital: "Brussels",
    population: "11 million",
    language: "Dutch, French, German",
    funFact: "The colors were taken from the coat of arms of the Duchy of Brabant!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Belgium"
  },
  {
    id: "ch",
    type: "flag",
    name: "Switzerland",
    country: "Switzerland",
    flagUrl: "https://flagcdn.com/w320/ch.png",
    imageUrl: "https://flagcdn.com/w320/ch.png",
    description: "A red square with a white cross in the center!",
    region: "Europe",
    capital: "Bern",
    population: "8.6 million",
    language: "German, French, Italian, Romansh",
    funFact: "It's one of only two square national flags in the world!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Switzerland"
  }
]; 