import { Flag } from '../types';

export const northAmericaFlags: Flag[] = [
  {
    id: "us",
    type: "flag",
    name: "United States",
    country: "United States",
    flagUrl: "https://flagcdn.com/w320/us.png",
    imageUrl: "https://flagcdn.com/w320/us.png",
    description: "The flag has 50 stars for the 50 states and 13 stripes for the original colonies!",
    region: "North America",
    capital: "Washington, D.C.",
    population: "331 million",
    language: "English",
    funFact: "The US flag was designed by a high school student!",
    funFactReference: "https://www.ushistory.org/betsy/flagfact.html"
  },
  {
    id: "ca",
    type: "flag",
    name: "Canada",
    country: "Canada",
    flagUrl: "https://flagcdn.com/w320/ca.png",
    imageUrl: "https://flagcdn.com/w320/ca.png",
    description: "A red maple leaf in the center of a white square between two red bands!",
    region: "North America",
    capital: "Ottawa",
    population: "38 million",
    language: "English, French",
    funFact: "The maple leaf has been a symbol of Canada since the 1700s!",
    funFactReference: "https://www.canada.ca/en/canadian-heritage/services/flag-canada-history.html"
  },
  {
    id: "mx",
    type: "flag",
    name: "Mexico",
    country: "Mexico",
    flagUrl: "https://flagcdn.com/w320/mx.png",
    imageUrl: "https://flagcdn.com/w320/mx.png",
    description: "Three vertical stripes of green, white, and red with an eagle in the center!",
    region: "North America",
    capital: "Mexico City",
    population: "126 million",
    language: "Spanish",
    funFact: "The eagle on the flag is based on an Aztec legend!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Mexico"
  },
  {
    id: "cr",
    type: "flag",
    name: "Costa Rica",
    country: "Costa Rica",
    flagUrl: "https://flagcdn.com/w320/cr.png",
    imageUrl: "https://flagcdn.com/w320/cr.png",
    description: "Five horizontal bands of blue, white, red, white, and blue!",
    region: "North America",
    capital: "San José",
    population: "5.1 million",
    language: "Spanish",
    funFact: "The colors were inspired by the French flag!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Costa-Rica"
  },
  {
    id: "pa",
    type: "flag",
    name: "Panama",
    country: "Panama",
    flagUrl: "https://flagcdn.com/w320/pa.png",
    imageUrl: "https://flagcdn.com/w320/pa.png",
    description: "Four squares with white and blue stars, and red and white solid colors!",
    region: "North America",
    capital: "Panama City",
    population: "4.3 million",
    language: "Spanish",
    funFact: "The stars represent the purity and peace of the country!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Panama"
  },
  {
    id: "jm",
    type: "flag",
    name: "Jamaica",
    country: "Jamaica",
    flagUrl: "https://flagcdn.com/w320/jm.png",
    imageUrl: "https://flagcdn.com/w320/jm.png",
    description: "A gold cross dividing the flag into four triangles of green and black!",
    region: "North America",
    capital: "Kingston",
    population: "2.9 million",
    language: "English",
    funFact: "It's the only national flag that doesn't contain red, white, or blue!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Jamaica"
  },
  {
    id: "cu",
    type: "flag",
    name: "Cuba",
    country: "Cuba",
    flagUrl: "https://flagcdn.com/w320/cu.png",
    imageUrl: "https://flagcdn.com/w320/cu.png",
    description: "Five horizontal stripes and a red triangle with a white star!",
    region: "North America",
    capital: "Havana",
    population: "11.3 million",
    language: "Spanish",
    funFact: "The design was inspired by the US flag!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Cuba"
  },
  {
    id: "do",
    type: "flag",
    name: "Dominican Republic",
    country: "Dominican Republic",
    flagUrl: "https://flagcdn.com/w320/do.png",
    imageUrl: "https://flagcdn.com/w320/do.png",
    description: "A centered white cross with blue and red rectangles, and the national coat of arms!",
    region: "North America",
    capital: "Santo Domingo",
    population: "10.8 million",
    language: "Spanish",
    funFact: "It's the only national flag with a Bible on it!",
    funFactReference: "https://www.britannica.com/topic/flag-of-the-Dominican-Republic"
  },
  {
    id: "ht",
    type: "flag",
    name: "Haiti",
    country: "Haiti",
    flagUrl: "https://flagcdn.com/w320/ht.png",
    imageUrl: "https://flagcdn.com/w320/ht.png",
    description: "Two horizontal stripes of blue and red with the national coat of arms in the center!",
    region: "North America",
    capital: "Port-au-Prince",
    population: "11.4 million",
    language: "French, Haitian Creole",
    funFact: "The flag was adopted after Haiti gained independence from France!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Haiti"
  },
  {
    id: "gt",
    type: "flag",
    name: "Guatemala",
    country: "Guatemala",
    flagUrl: "https://flagcdn.com/w320/gt.png",
    imageUrl: "https://flagcdn.com/w320/gt.png",
    description: "Three vertical stripes of light blue, white, and light blue with the national coat of arms!",
    region: "North America",
    capital: "Guatemala City",
    population: "17.2 million",
    language: "Spanish",
    funFact: "The flag's colors represent the Pacific and Atlantic oceans!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Guatemala"
  }
]; 