import { Flag } from '../types';

export const southAmericaFlags: Flag[] = [
  {
    id: "br",
    type: "flag",
    name: "Brazil",
    country: "Brazil",
    flagUrl: "https://flagcdn.com/w320/br.png",
    imageUrl: "https://flagcdn.com/w320/br.png",
    description: "A green field with a yellow diamond and a blue circle with stars!",
    region: "South America",
    capital: "Brasília",
    population: "213 million",
    language: "Portuguese",
    funFact: "The stars represent the night sky over Rio de Janeiro on November 15, 1889!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Brazil"
  },
  {
    id: "ar",
    type: "flag",
    name: "Argentina",
    country: "Argentina",
    flagUrl: "https://flagcdn.com/w320/ar.png",
    imageUrl: "https://flagcdn.com/w320/ar.png",
    description: "Three horizontal stripes of light blue, white, and light blue with a sun in the center!",
    region: "South America",
    capital: "Buenos Aires",
    population: "45 million",
    language: "Spanish",
    funFact: "The sun symbol represents the Inca sun god Inti!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Argentina"
  },
  {
    id: "pe",
    type: "flag",
    name: "Peru",
    country: "Peru",
    flagUrl: "https://flagcdn.com/w320/pe.png",
    imageUrl: "https://flagcdn.com/w320/pe.png",
    description: "Three vertical stripes of red, white, and red with the national coat of arms!",
    region: "South America",
    capital: "Lima",
    population: "33 million",
    language: "Spanish, Quechua",
    funFact: "The flag was inspired by the colors of the vicuña, a native animal!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Peru"
  },
  {
    id: "co",
    type: "flag",
    name: "Colombia",
    country: "Colombia",
    flagUrl: "https://flagcdn.com/w320/co.png",
    imageUrl: "https://flagcdn.com/w320/co.png",
    description: "Three horizontal stripes of yellow, blue, and red!",
    region: "South America",
    capital: "Bogotá",
    population: "51 million",
    language: "Spanish",
    funFact: "The yellow stripe takes up half of the flag's height!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Colombia"
  },
  {
    id: "cl",
    type: "flag",
    name: "Chile",
    country: "Chile",
    flagUrl: "https://flagcdn.com/w320/cl.png",
    imageUrl: "https://flagcdn.com/w320/cl.png",
    description: "Two horizontal stripes of white and red with a blue square and white star!",
    region: "South America",
    capital: "Santiago",
    population: "19 million",
    language: "Spanish",
    funFact: "The flag is known as 'La Estrella Solitaria' (The Lone Star)!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Chile"
  },
  {
    id: "ve",
    type: "flag",
    name: "Venezuela",
    country: "Venezuela",
    flagUrl: "https://flagcdn.com/w320/ve.png",
    imageUrl: "https://flagcdn.com/w320/ve.png",
    description: "Three horizontal stripes of yellow, blue, and red with an arc of stars!",
    region: "South America",
    capital: "Caracas",
    population: "28 million",
    language: "Spanish",
    funFact: "The stars represent the original seven provinces that declared independence!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Venezuela"
  },
  {
    id: "ec",
    type: "flag",
    name: "Ecuador",
    country: "Ecuador",
    flagUrl: "https://flagcdn.com/w320/ec.png",
    imageUrl: "https://flagcdn.com/w320/ec.png",
    description: "Three horizontal stripes of yellow, blue, and red with the national coat of arms!",
    region: "South America",
    capital: "Quito",
    population: "17 million",
    language: "Spanish",
    funFact: "The condor on the coat of arms represents power and strength!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Ecuador"
  },
  {
    id: "bo",
    type: "flag",
    name: "Bolivia",
    country: "Bolivia",
    flagUrl: "https://flagcdn.com/w320/bo.png",
    imageUrl: "https://flagcdn.com/w320/bo.png",
    description: "Three horizontal stripes of red, yellow, and green with the national coat of arms!",
    region: "South America",
    capital: "Sucre",
    population: "12 million",
    language: "Spanish, Quechua, Aymara",
    funFact: "The flag has two official versions - one with and one without the coat of arms!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Bolivia"
  },
  {
    id: "py",
    type: "flag",
    name: "Paraguay",
    country: "Paraguay",
    flagUrl: "https://flagcdn.com/w320/py.png",
    imageUrl: "https://flagcdn.com/w320/py.png",
    description: "Three horizontal stripes of red, white, and blue with different emblems on each side!",
    region: "South America",
    capital: "Asunción",
    population: "7 million",
    language: "Spanish, Guaraní",
    funFact: "It's the only national flag with different emblems on its obverse and reverse sides!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Paraguay"
  },
  {
    id: "uy",
    type: "flag",
    name: "Uruguay",
    country: "Uruguay",
    flagUrl: "https://flagcdn.com/w320/uy.png",
    imageUrl: "https://flagcdn.com/w320/uy.png",
    description: "Nine horizontal stripes of white and blue with a sun in the corner!",
    region: "South America",
    capital: "Montevideo",
    population: "3.5 million",
    language: "Spanish",
    funFact: "The nine stripes represent the original nine departments of Uruguay!",
    funFactReference: "https://www.britannica.com/topic/flag-of-Uruguay"
  }
]; 